spring:
  application:
    name: batch
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/security_jwt
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true